language: R
sudo: true
cache: packages

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpoppler-cpp-dev

after_success: 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; 
    then 
      Rscript -e 'covr::coveralls(type = "all")'; 
    fi
warnings_are_errors: yes
before_deploy: 
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; 
    then 
      rm -f *.tar.gz; 
    fi
r_check_args: --as-cran --install-args=--build
deploy:
  provider: releases
  skip_cleanup: yes
  file_glob: yes
  file: didactr*.t*gz
  'on':
    tags: yes
    repo: muschellij2/didactr

